services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel
    command: >
      sh -c "chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache && php-fpm"

  web:
    image: nginx:latest
    container_name: laravel_web
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - laravel
    depends_on:
      - app

networks:
  laravel: